### ISSUE TITLE
mapfish-print 3.26.0 - Problem in yaml reading

### ISSUE THREAD

**Issue by svahul** [mapfish/mapfish-print#1595]
**Context**

- MapFish print version: 3.26.0

**Describe the bug**

I have read, that there was a problem with snakeyaml in reading the config.yaml. In the version 3.23 the problem was solved using the war file (https://github.com/openoereb/pyramid_oereb_mfp/issues/68).

I have tried to migrate the print sever to 3.26.0. When reading the capabilities, the same problem still pears:

`Root Cause: org.yaml.snakeyaml.error.YAMLException: Number of aliases for non-scalar nodes exceeds the specified max=50
`

Will this problem be solved for MapFish print version 3.26.0?

**How to reproduce**

- Download war: https://github.com/mapfish/mapfish-print/releases/download/release%2F3.26.0/print-servlet-3.26.0.war

- Delete empty line in manifest

- Add print-apps folder of a previous version

- get capabillities.

**Comment by jwkaltz** [comment]
If you have a configuration file which has more than 50 nodes, you need to use an environment variable PRINT_YAML_MAX_ALIASES which you set to the maximum of nodes which should be allowed in your print configuration.

This additional configuration is necessary due to a new version of the YAML parsing library that MapFish Print is using.

**Comment by jwkaltz** [comment]
@svahul if your concern is in the pyramid_oereb_mfp project, then please note that a bit of documentation was added about this issue in the readme (https://github.com/openoereb/pyramid_oereb_mfp).

**Comment by svahul** [comment]
Thank you @jwkaltz. It works that way.
