### ISSUE TITLE
Maven dependency unavailable for last versions

### ISSUE THREAD

**Issue by jusabatier** [mapfish/mapfish-print#2633]
I'm trying to add a dependency to print-lib in a maven project, but I can't find any public repository with last version (3.29.4).

I've found that it's available on Github Packages, but this isn't public and need specific configurations to make it work.

Is it planned to have them available in maven's central repository ?
Jitpack can also be a solution, but currently the build doesn't work : https://jitpack.io/com/github/mapfish/mapfish-print/3.29.4/build.log
I don't know gradle very well, is it hard to fix ?

**Comment by sbrunner** [comment]
> I've found that it's available on Github Packages, but this isn't public

Why do you say that isn't public?

**Comment by pmauduit** [comment]
> Why do you say that isn't public?

We had a talk with @jusabatier earlier on the #georchestra IRC channel on this topic, what he meant is that even if the packages are made available on the github maven repository (https://github.com/orgs/mapfish/packages), they are not indexed by mvnrepository.com, nor made available publicly from the regular maven tools, at least without a bit of configuration, because the github maven repository requires a token to be able to grab the dependencies being published: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry

if we look at `org.mapfish.print/print-lib` (https://mvnrepository.com/artifact/org.mapfish.print/print-lib) last release known to the maven central repositories is the `3.22.0` from the 7th. of january 2020, which does not match with the release page on github. 

I guess the main issue here is: how to have the latest version being publicly available from a maven repo which does not require any configuration / token or whatever else  (maven central would be perfect) ?

**Comment by sbrunner** [comment]
The version 3.30 looks to be successfully built: https://jitpack.io/#mapfish/mapfish-print :-)
