### ISSUE TITLE
incohérence d'échelle sur une impression

### ISSUE THREAD

**Issue by didier-coignet-dict** [mapfish/mapfish-print#264]
Dans mapfish-print 3.1.2 nous avons des problème d'incohérence d'échelles sur certains de nos modèles d'impression.
Voici [un exemple](https://gist.github.com/didier-coignet-dict/e67444adbb17a1c0b13c/raw/80161aa1c36d56e6289043f3c351f3e6a32ffe54/scalebarIncoherente.zip)  qui reproduit le comportement actuel.

La carte est imprimée au 1:1500 environs , MapfishContext.getScaleDenominator() retourne 1:2000, et La scalebar à une échelle de 1:1000.
Le résultat attendu est 1:2000 nous utilisons la stratégie HIGHER_SCALE pour le snapping et zoomToFeatures "extent".

Le fichier expected_output/requestData.png correspond à l'état incohérent et non à l'état attendu.

**Comment by sbrunner** [comment]
Some issue will be fixed by #286 and #293.

Now we can do your example in geodetic scale calculation or not.
The issue is that you use a world projection than the scale in the projection is valid only on the equator.
Then it is advise to use geodetic scale calculation, but the zoomLevelSnapStrategy will snap on scale in the projection not on geodetic scale.

Should I find a way to snap on geodetic scales or is it OK for you like that ?

**Comment by didier-coignet-dict** [comment]
Thanks great work ! 
It would be great if we can find a way to snap on geodetic scales also.

**Comment by sbrunner** [comment]
Added to the pull request #293  :-)

**Comment by tsauerwein** [comment]
Can this issue be closed?
